### ISSUE TITLE
mp4

### ISSUE THREAD

**Issue by paulhovey** [stretchr/filetypes.js#3]
When I look up the mimetype for extension ".mp4", it returns me "application/mp4".  It seems the default should be "video/mp4".  From http://www.rfc-editor.org/rfc/rfc4337.txt :

>2.  Selection of MIME Types for MP4 Files
>
>   The MIME types to be assigned to MP4 files are selected according to
>   the contents.  Basic guidelines for selecting MIME types are as
>   follows:
>
>   a) if the file contains neither visual nor audio presentations, but
>      only, for example, MPEG-J or MPEG-7, use application/mp4;
>
>   b) for all other files, including those that have MPEG-J, etc., in
>      addition to video or audio streams, video/mp4 should be used;
>      however:
>
>   c) for files with audio but no visual aspect, including those that
>      have MPEG-J, etc., in addition to audio streams, audio/mp4 may be
>      used.
>
>   In any case, these indicate files conforming to the "MP4"
>   specification, ISO/IEC 14496-1:2000, systems file format.

Assuming the .mp4 file has either video or audio, it should be video/mp4 .  I propose making the "video/mp4" return for .mp4 filetypes instead of "application/mp4".  Any thoughts?

Thanks,
Paul

**Comment by matryer** [comment]
Seems sensible to me. PR?

**Comment by matryer** [comment]
Thanks.
